kind: Service
apiVersion: v1
metadata:
  name: railsapp-db
  labels:
    app.kubernetes.io/name: railsapp-db
    process: db
spec:
  selector:
    app.kubernetes.io/name: railsapp-db
    process: db
  type: NodePort
  #type: LoadBalancer
  ports:
  - name: railsdb
    protocol: TCP
    port: 5432
    targetPort: 5432
