apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: railsapp
  namespace: "default"
  labels:
    app.kubernetes.io/name: railsapp-deployment
    process: web
  #annotations:
  #  kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: rails.devops.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: railsapp-service
            port:
              number: 3000
