kind: Service
apiVersion: v1
metadata:
  name: railsapp-service
  labels:
    app.kubernetes.io/name: railsapp-deployment
    process: web
spec:
  selector:
    app.kubernetes.io/name: railsapp-deployment
    process: web
  type: NodePort
  #type: LoadBalancer
  ports:
  - name: railsapp
    protocol: TCP
    port: 3000
    targetPort: 3000
